# GraphRAG 配置文件
model:
  # LLM 配置
  llm_model: "gpt-3.5-turbo"
  embedding_model: "text-embedding-ada-002"
  temperature: 0.1
  max_tokens: 2000
  
  # API 配置
  api_key: "#############"
  base_url: "https://idealab.alibaba-inc.com/api/openai/v1"

  # 本地模型配置（可选）
  local_llm: false
  local_embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

graph:
  # 图构建参数
  chunk_size: 1000
  chunk_overlap: 200
  max_entities_per_chunk: 10
  similarity_threshold: 0.8
  
  # 社区检测参数
  community_algorithm: "leiden"
  resolution: 1.0

retrieval:
  # 检索参数
  top_k_entities: 20
  top_k_communities: 5
  max_context_length: 8000
  
storage:
  # 存储配置
  working_dir: "./graphrag_cache"
  enable_cache: true
  
dataset:
  # 数据集配置
  name: "squad"  # 或 "hotpot_qa", "natural_questions"
  max_samples: 1000
  split: "train"
